version: '3.8'

services:
  nginx-app:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - database
    networks:
      - app-network

  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      PGDATA: /var/lib/pgsql/15/data
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/pgsql/15/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local
  nginx-logs:
    driver: local

networks:
  app-network:
    driver: bridge
