apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: system1
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
